name: Testing
on:
  pull_request:
    branches:
      - master
      - alpha
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react-version: [18, 19]
    env:
      BS_ACCESS_KEY: ${{ secrets.BS_ACCESS_KEY }}
      BS_USERNAME: ${{ secrets.BS_USERNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 14
      - name: Installing Dependencies
        run: yarn install --frozen-lockfile
      - name: Install React ${{ matrix.react-version }}
        run: yarn add react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }} --dev
      - name: Checking File Size
        run: yarn check:size
      - name: Checking Linting Rules
        run: yarn check:lint
      - name: Checking Types
        run: yarn check:types
      - name: Running Unit Tests
        run: yarn test:unit
      - name: Testing SSR
        run: yarn test:create:ssr
      - name: Testing in Modern Browsers (BrowserStack)
        run: yarn test:bs:modern
      - name: Testing in Legacy Browsers (BrowserStack)
        run: yarn test:bs:legacy
